include $(THEOS)/makefiles/common.mk

TOOL_NAME = OITDumpTrigger

OITDumpTrigger_FILES = main.m
OITDumpTrigger_CFLAGS = -fobjc-arc
OITDumpTrigger_FRAMEWORKS = Foundation
OITDumpTrigger_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
