include $(THEOS)/makefiles/common.mk

TOOL_NAME = OITIRestoreGestalt

OITIRestoreGestalt_FILES = main.m
OITIRestoreGestalt_CFLAGS = -fobjc-arc
OITIRestoreGestalt_FRAMEWORKS = Foundation
OITIRestoreGestalt_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
